
#ifndef GRAMODS_GRAPHICS_SAVEVIEW
#define GRAMODS_GRAPHICS_SAVEVIEW

// Required before gmCore/OFactory.hh for some compilers
#include <gmCore/io_size.hh>

#include <gmGraphics/View.hh>

BEGIN_NAMESPACE_GMGRAPHICS;

/**
   The SaveView is a view that saves the image generated by another
   view.
*/
class SaveView
  : public View {

public:

  SaveView();

  /**
     Forwards rendering to the sub view and saves the result.
  */
  void renderFullPipeline(ViewSettings settings) override;

  /**
     Propagates the specified visitor.

     @see Object::Visitor
  */
  void traverse(Visitor *visitor) override;

  /**
     Sets the file path to save the view to.

     If a sequence of image files should be saved, then set this as a
     fprint formatted template, for example "frame_%06d.png". Default
     value is "SaveView.png".

     Supported suffixes are png, jpeg, exr, tiff and pfm. Some of
     these support alpha and some support float:

     | Format | Alpha | Float |
     |:-------|:-----:|:-----:|
     | PNG    |   *   |       |
     | JPEG   |       |       |
     | EXR    |       |   *   |
     | TIFF   |   *   |   *   |
     | PFM    |       |   *   |

     \gmXmlTag{gmGraphics,SaveView,file}
  */
  void setFile(std::filesystem::path file);

  /**
     Sets the resolution to render and save at, regarless of
     resolution of the view itself. Default is to use the view
     resolution.

     \gmXmlTag{gmGraphics,SaveView,resolution}
  */
  void setResolution(gmCore::size2 res);

  /**
     Set to true if the pixel data should be read off and saved in
     floating point format. Default is off.
  */
  void setUseFloat(bool on);

  /**
     Returns true iff the pixel data are read off and saved in
     floating point format, false otherwise.
  */
  bool getUseFloat();

  /**
     Set to true if the alpha channel should be read off and
     saved. Default is false.
  */
  void setUseAlpha(bool on);

  /**
     Returns true iff the alpha channel is read off and saved.
  */
  bool getUseAlpha();

  /**
     Activates or deactivates automatic exit when the view has been
     saved. When converting animation, consider using automatic exit
     in the ImageTexture. Default is false.

     \gmXmlTag{gmGraphics,SaveView,exit}
  */
  void setExit(bool on);

  /**
     Adds a view that should be saved to file.

     \gmXmlTag{gmGraphics,SaveView,view}
  */
  void addView(std::shared_ptr<View> view);

  GM_OFI_DECLARE;

private:

  struct Impl;
  std::unique_ptr<Impl> _impl;

};

END_NAMESPACE_GMGRAPHICS;

#endif
