
#ifndef GRAMODS_GRAPHICS_SAVEVIEW
#define GRAMODS_GRAPHICS_SAVEVIEW

#include <gmGraphics/View.hh>

BEGIN_NAMESPACE_GMGRAPHICS;

/**
   The SaveView is a view that saves the image generated by another
   view.
*/
class SaveView
  : public View {

public:

  SaveView();

  /**
     Forwards rendering to the sub view and saves the result.
  */
  void renderFullPipeline(ViewSettings settings);

  /**
     Sets the file path to save the view to. If a sequence of image
     files should be saved, set this as a fprint formatted template.
  */
  void setFile(std::string file);

  /**
     Sets the view that should be saved to file.
  */
  void setView(std::shared_ptr<View> view);

  GM_OFI_DECLARE;

private:

  class Impl;
  std::unique_ptr<Impl> _impl;

};

END_NAMESPACE_GMGRAPHICS;

#endif
