
FUNCTION(get_sources_and_headers)

  FILE(GLOB_RECURSE HEADERS_ABSOLUTE
    ${CMAKE_CURRENT_SOURCE_DIR}/include/*.hh
    )
  FILE(GLOB_RECURSE HEADERS_RELATIVE
    RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/include/*.hh
    )
  SET(HEADERS_MAGIC ${HEADERS_RELATIVE})
  LIST(TRANSFORM HEADERS_MAGIC REPLACE
    "(.+)" "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/\\1>$<INSTALL_INTERFACE:\\1>")

  FILE(GLOB_RECURSE SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.hh
    )

  SET(SOURCES ${SOURCES} PARENT_SCOPE)
  SET(HEADERS_ABSOLUTE ${HEADERS_ABSOLUTE} PARENT_SCOPE)
  SET(HEADERS_MAGIC ${HEADERS_MAGIC} PARENT_SCOPE)
ENDFUNCTION()
