
FUNCTION(make_dependencies_relocatable RET_LIST)

  FOREACH(LIB ${ARGN})
    IF (EXISTS ${LIB})
      GET_FILENAME_COMPONENT(LIB_FILE ${LIB} NAME)
      LIST(APPEND PUBLIC_LIBS_MAGIC
        "$<BUILD_INTERFACE:${LIB}>$<INSTALL_INTERFACE:${LIB_FILE}>")
    ELSE()
      LIST(APPEND PUBLIC_LIBS_MAGIC "${LIB}")
    ENDIF()
  ENDFOREACH()

  SET("${RET_LIST}" ${PUBLIC_LIBS_MAGIC} PARENT_SCOPE)
ENDFUNCTION()
