
stages:
  - build
  - test

BuildMini:
  image: $CI_REGISTRY/karlu20/gramods:20.04-mini
  stage: build
  script:
    - apt-get update
    - DEBIAN_FRONTEND="noninteractive" apt-get -y install cmake build-essential ninja-build libgtest-dev
    - cmake -S . -B build
      -D gramods_TEST_gmGraphics=OFF
      -G Ninja
      -D CMAKE_BUILD_TYPE=Release
    - ninja -j 1 -C build
    - ninja -C build test

BuildMaxi:
  image: $CI_REGISTRY/karlu20/gramods/22.04-maxi
  stage: build
  script:
    - apt-get update
    - DEBIAN_FRONTEND="noninteractive" apt-get -y install cmake git build-essential ninja-build libgtest-dev libtinyxml2-dev libsdl2-dev libsdl2-ttf-dev libeigen3-dev libglew-dev libasio-dev libopenscenegraph-dev libuvc-dev libfreeimage-dev inkscape pipenv
    - DEBIAN_FRONTEND="noninteractive" apt-get -y --purge remove pipenv
    - pip install pipenv
    - cmake -S . -B build
      -D gramods_TEST_gmGraphics=OFF
      -D CPACK_BINARY_DEB=ON
      -D TinyXML2_DIR:PATH=$(pwd)/cmake_modules/tinyxml2-shared/
      -D FreeImage_DIR:PATH=$(pwd)/cmake_modules/freeimage-shared/
      -D VRPN_DIR:PATH=$(pwd)/cmake_modules/vrpn-static/
      -D SDL2_DIR:PATH=$(pwd)/cmake_modules/sdl2-shared/
      -D CMAKE_PREFIX_PATH:PATH=/vrpn-install/
      -D CPACK_DEBIAN_PACKAGE_DEPENDS="libtinyxml2-6a, libsdl2-2.0-0, libsdl2-ttf-2.0-0, libglew2.1, libopenscenegraph160, libuvc0, libfreeimage3"
      -G Ninja
      -D CMAKE_BUILD_TYPE=Release
    - mkdir -p modules/gmGraphics/resources/
    - ninja -j 1 -C build
    - ./build/test/gmCore/test_gmCore --gtest_output=xml:report-gmCore.xml
    - ./build/test/gmMisc/test_gmMisc --gtest_output=xml:report-gmMisc.xml
    - ./build/test/gmNetwork/test_gmNetwork --gtest_output=xml:report-gmNetwork.xml
    - ./build/test/gmTouch/test_gmTouch --gtest_output=xml:report-gmTouch .xml
    - ./build/test/gmTrack/test_gmTrack --gtest_output=xml:report-gmTrack.xml
    - ninja -C build test
    - ninja -C build package
  artifacts:
    paths: ['build/*gramods*.deb']
    expire_in: 2 hrs
    reports:
      junit:
        - report-gmCore.xml
        - report-gmMisc.xml
        - report-gmNetwork.xml
        - report-gmTouch.xml
        - report-gmTrack.xml

TestInstall:
  image: $CI_REGISTRY/karlu20/gramods:20.04-mini
  stage: test
  script:
    - apt update
    - apt install -y ./build/*gramods*.deb
  dependencies:
    - BuildMaxi
