# Final resort if no "real" sdl2-config.cmake file is available

FIND_PATH(SDL2_INCLUDE_DIR SDL.h
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES include/SDL2 include
  )

FIND_LIBRARY(SDL2_LIBRARY_RELEASE
	NAMES SDL2
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES lib64 lib
  )
FIND_LIBRARY(SDL2_LIBRARY_DEBUG
	NAMES SDL2d
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES lib64 lib
  )

FIND_LIBRARY(SDL2MAIN_LIBRARY_RELEASE
	NAMES SDL2main
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES lib64 lib
	)
FIND_LIBRARY(SDL2MAIN_LIBRARY_DEBUG
	NAMES SDL2maind
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES lib64 lib
	)

ADD_LIBRARY(SDL2::SDL2 SHARED IMPORTED)
IF (SDL2_INCLUDE_DIR AND (SDL2_LIBRARY_RELEASE OR SDL2_LIBRARY_DEBUG))
  SET_TARGET_PROPERTIES(SDL2::SDL2 PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${SDL2_INCLUDE_DIR}
    IMPORTED_LOCATION_RELEASE ${SDL2_LIBRARY_RELEASE}
    IMPORTED_LOCATION_DEBUG ${SDL2_LIBRARY_DEBUG}
    IMPORTED_LOCATION_RELWITHDEBINFO ${SDL2_LIBRARY_RELEASE}
    )
ELSE()
  MESSAGE(SEND_ERROR "Could not set properties of target SDL2::SDL2 - set SDL2_INCLUDE_DIR and SDL2_LIBRARY or unset SDL2_DIR")
ENDIF()

ADD_LIBRARY(SDL2::SDL2main STATIC IMPORTED)
IF (SDL2MAIN_LIBRARY_RELEASE OR SDL2MAIN_LIBRARY_DEBUG)
  SET_TARGET_PROPERTIES(SDL2::SDL2main PROPERTIES
    IMPORTED_LOCATION_RELEASE ${SDL2MAIN_LIBRARY_RELEASE}
    IMPORTED_LOCATION_DEBUG ${SDL2MAIN_LIBRARY_DEBUG}
    IMPORTED_LOCATION_RELWITHDEBINFO ${SDL2MAIN_LIBRARY_RELEASE}
    )
ELSE()
  MESSAGE(SEND_ERROR "Could not set properties of target SDL2::SDL2main - set SDL2MAIN_LIBRARY or unset SDL2_DIR")
ENDIF()
