# Final resort if no "real" sdl2-config.cmake file is available

FIND_PATH(SDL2_INCLUDE_DIR SDL.h
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES include/SDL2 include
  )

FIND_LIBRARY(SDL2_LIBRARY
	NAMES SDL2
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES lib64 lib
  )

FIND_LIBRARY(SDL2MAIN_LIBRARY
	NAMES SDL2main
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES lib64 lib
	)

ADD_LIBRARY(SDL2::SDL2 SHARED IMPORTED)
IF (SDL2_INCLUDE_DIR AND SDL2_LIBRARY)
SET_TARGET_PROPERTIES(SDL2::SDL2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES ${SDL2_INCLUDE_DIR}
  IMPORTED_LOCATION ${SDL2_LIBRARY})
ELSE()
  MESSAGE(SEND_ERROR "Could not set properties of target SDL2::SDL2 - set SDL2_INCLUDE_DIR and SDL2_LIBRARY or unset SDL2_DIR")
ENDIF()

ADD_LIBRARY(SDL2::SDL2main STATIC IMPORTED)
IF (SDL2MAIN_LIBRARY)
  SET_TARGET_PROPERTIES(SDL2::SDL2main PROPERTIES
    IMPORTED_LOCATION ${SDL2MAIN_LIBRARY})
ELSE()
  MESSAGE(SEND_ERROR "Could not set properties of target SDL2::SDL2main - set SDL2MAIN_LIBRARY or unset SDL2_DIR")
ENDIF()
