
#include <gmGraphics/GLUtils.hh>

#include <gmCore/Console.hh>

#include <GL/glew.h>
#include <GL/gl.h>

BEGIN_NAMESPACE_GMGRAPHICS;

bool GLUtils::check_shader_program(GLuint program_id) {

  GLint msg_data_len;
  glGetProgramiv(program_id, GL_INFO_LOG_LENGTH, &msg_data_len);

  if (!msg_data_len)
    msg_data_len = 64;

  std::vector<GLchar> msg_data(msg_data_len, '\0');
  
  GLint msg_len;
  glGetProgramInfoLog(program_id, msg_data_len, &msg_len, msg_data.data());

  GLint status;
  glValidateProgram(program_id);
  glGetProgramiv(program_id, GL_VALIDATE_STATUS, &status);

  if (status) {
    if (msg_len)
      GM_DBG1("OpenGL", msg_data.data());
    return true;
  }

  if (!msg_len)
    GM_ERR("OpenGL", "shader program not valid");
  else
    GM_ERR("OpenGL", msg_data.data());

  return false;
}

bool GLUtils::check_framebuffer() {
	GLenum status;
	status = glCheckFramebufferStatus(GL_DRAW_FRAMEBUFFER);
	switch(status) {
	case GL_FRAMEBUFFER_COMPLETE:
    GM_DBG1("OpenGL", "Frame buffer complete");
		return true;

	case GL_FRAMEBUFFER_UNSUPPORTED:
    GM_ERR("OpenGL", "Frame buffer unsupported");
		break;

	default:
    GM_ERR("OpenGL", "Frame buffer incomplete");
	}
  return false;
}

int GLUtils::nextPowerOfTwo(int v) {
  v--;
  v |= v >> 1;
  v |= v >> 2;
  v |= v >> 4;
  v |= v >> 8;
  v |= v >> 16;
  v++;
  return v;
}

std::string GLUtils::toString(GLenum v) {

#define ALT(X)                                                                 \
  if (v == X) return #X;

  ALT(GL_FALSE);
  ALT(GL_TRUE);

  /* Data types */
  ALT(GL_BYTE);
  ALT(GL_UNSIGNED_BYTE);
  ALT(GL_SHORT);
  ALT(GL_UNSIGNED_SHORT);
  ALT(GL_INT);
  ALT(GL_UNSIGNED_INT);
  ALT(GL_FLOAT);
  ALT(GL_2_BYTES);
  ALT(GL_3_BYTES);
  ALT(GL_4_BYTES);
  ALT(GL_DOUBLE);

  /* Primitives */
  ALT(GL_POINTS);
  ALT(GL_LINES);
  ALT(GL_LINE_LOOP);
  ALT(GL_LINE_STRIP);
  ALT(GL_TRIANGLES);
  ALT(GL_TRIANGLE_STRIP);
  ALT(GL_TRIANGLE_FAN);
  ALT(GL_QUADS);
  ALT(GL_QUAD_STRIP);
  ALT(GL_POLYGON);

  /* Vertex Arrays */
  ALT(GL_VERTEX_ARRAY);
  ALT(GL_NORMAL_ARRAY);
  ALT(GL_COLOR_ARRAY);
  ALT(GL_INDEX_ARRAY);
  ALT(GL_TEXTURE_COORD_ARRAY);
  ALT(GL_EDGE_FLAG_ARRAY);
  ALT(GL_VERTEX_ARRAY_SIZE);
  ALT(GL_VERTEX_ARRAY_TYPE);
  ALT(GL_VERTEX_ARRAY_STRIDE);
  ALT(GL_NORMAL_ARRAY_TYPE);
  ALT(GL_NORMAL_ARRAY_STRIDE);
  ALT(GL_COLOR_ARRAY_SIZE);
  ALT(GL_COLOR_ARRAY_TYPE);
  ALT(GL_COLOR_ARRAY_STRIDE);
  ALT(GL_INDEX_ARRAY_TYPE);
  ALT(GL_INDEX_ARRAY_STRIDE);
  ALT(GL_TEXTURE_COORD_ARRAY_SIZE);
  ALT(GL_TEXTURE_COORD_ARRAY_TYPE);
  ALT(GL_TEXTURE_COORD_ARRAY_STRIDE);
  ALT(GL_EDGE_FLAG_ARRAY_STRIDE);
  ALT(GL_VERTEX_ARRAY_POINTER);
  ALT(GL_NORMAL_ARRAY_POINTER);
  ALT(GL_COLOR_ARRAY_POINTER);
  ALT(GL_INDEX_ARRAY_POINTER);
  ALT(GL_TEXTURE_COORD_ARRAY_POINTER);
  ALT(GL_EDGE_FLAG_ARRAY_POINTER);
  ALT(GL_V2F);
  ALT(GL_V3F);
  ALT(GL_C4UB_V2F);
  ALT(GL_C4UB_V3F);
  ALT(GL_C3F_V3F);
  ALT(GL_N3F_V3F);
  ALT(GL_C4F_N3F_V3F);
  ALT(GL_T2F_V3F);
  ALT(GL_T4F_V4F);
  ALT(GL_T2F_C4UB_V3F);
  ALT(GL_T2F_C3F_V3F);
  ALT(GL_T2F_N3F_V3F);
  ALT(GL_T2F_C4F_N3F_V3F);
  ALT(GL_T4F_C4F_N3F_V4F);

  /* Matrix Mode */
  ALT(GL_MATRIX_MODE);
  ALT(GL_MODELVIEW);
  ALT(GL_PROJECTION);
  ALT(GL_TEXTURE);

  /* Points */
  ALT(GL_POINT_SMOOTH);
  ALT(GL_POINT_SIZE);
  ALT(GL_POINT_SIZE_GRANULARITY);
  ALT(GL_POINT_SIZE_RANGE);

  /* Lines */
  ALT(GL_LINE_SMOOTH);
  ALT(GL_LINE_STIPPLE);
  ALT(GL_LINE_STIPPLE_PATTERN);
  ALT(GL_LINE_STIPPLE_REPEAT);
  ALT(GL_LINE_WIDTH);
  ALT(GL_LINE_WIDTH_GRANULARITY);
  ALT(GL_LINE_WIDTH_RANGE);

  /* Polygons */
  ALT(GL_POINT);
  ALT(GL_LINE);
  ALT(GL_FILL);
  ALT(GL_CW);
  ALT(GL_CCW);
  ALT(GL_FRONT);
  ALT(GL_BACK);
  ALT(GL_POLYGON_MODE);
  ALT(GL_POLYGON_SMOOTH);
  ALT(GL_POLYGON_STIPPLE);
  ALT(GL_EDGE_FLAG);
  ALT(GL_CULL_FACE);
  ALT(GL_CULL_FACE_MODE);
  ALT(GL_FRONT_FACE);
  ALT(GL_POLYGON_OFFSET_FACTOR);
  ALT(GL_POLYGON_OFFSET_UNITS);
  ALT(GL_POLYGON_OFFSET_POINT);
  ALT(GL_POLYGON_OFFSET_LINE);
  ALT(GL_POLYGON_OFFSET_FILL);

  /* Display Lists */
  ALT(GL_COMPILE);
  ALT(GL_COMPILE_AND_EXECUTE);
  ALT(GL_LIST_BASE);
  ALT(GL_LIST_INDEX);
  ALT(GL_LIST_MODE);

  /* Depth buffer */
  ALT(GL_NEVER);
  ALT(GL_LESS);
  ALT(GL_EQUAL);
  ALT(GL_LEQUAL);
  ALT(GL_GREATER);
  ALT(GL_NOTEQUAL);
  ALT(GL_GEQUAL);
  ALT(GL_ALWAYS);
  ALT(GL_DEPTH_TEST);
  ALT(GL_DEPTH_BITS);
  ALT(GL_DEPTH_CLEAR_VALUE);
  ALT(GL_DEPTH_FUNC);
  ALT(GL_DEPTH_RANGE);
  ALT(GL_DEPTH_WRITEMASK);
  ALT(GL_DEPTH_COMPONENT);

  /* Lighting */
  ALT(GL_LIGHTING);
  ALT(GL_LIGHT0);
  ALT(GL_LIGHT1);
  ALT(GL_LIGHT2);
  ALT(GL_LIGHT3);
  ALT(GL_LIGHT4);
  ALT(GL_LIGHT5);
  ALT(GL_LIGHT6);
  ALT(GL_LIGHT7);
  ALT(GL_SPOT_EXPONENT);
  ALT(GL_SPOT_CUTOFF);
  ALT(GL_CONSTANT_ATTENUATION);
  ALT(GL_LINEAR_ATTENUATION);
  ALT(GL_QUADRATIC_ATTENUATION);
  ALT(GL_AMBIENT);
  ALT(GL_DIFFUSE);
  ALT(GL_SPECULAR);
  ALT(GL_SHININESS);
  ALT(GL_EMISSION);
  ALT(GL_POSITION);
  ALT(GL_SPOT_DIRECTION);
  ALT(GL_AMBIENT_AND_DIFFUSE);
  ALT(GL_COLOR_INDEXES);
  ALT(GL_LIGHT_MODEL_TWO_SIDE);
  ALT(GL_LIGHT_MODEL_LOCAL_VIEWER);
  ALT(GL_LIGHT_MODEL_AMBIENT);
  ALT(GL_FRONT_AND_BACK);
  ALT(GL_SHADE_MODEL);
  ALT(GL_FLAT);
  ALT(GL_SMOOTH);
  ALT(GL_COLOR_MATERIAL);
  ALT(GL_COLOR_MATERIAL_FACE);
  ALT(GL_COLOR_MATERIAL_PARAMETER);
  ALT(GL_NORMALIZE);

  /* User clipping planes */
  ALT(GL_CLIP_PLANE0);
  ALT(GL_CLIP_PLANE1);
  ALT(GL_CLIP_PLANE2);
  ALT(GL_CLIP_PLANE3);
  ALT(GL_CLIP_PLANE4);
  ALT(GL_CLIP_PLANE5);

  /* Accumulation buffer */
  ALT(GL_ACCUM_RED_BITS);
  ALT(GL_ACCUM_GREEN_BITS);
  ALT(GL_ACCUM_BLUE_BITS);
  ALT(GL_ACCUM_ALPHA_BITS);
  ALT(GL_ACCUM_CLEAR_VALUE);
  ALT(GL_ACCUM);
  ALT(GL_ADD);
  ALT(GL_LOAD);
  ALT(GL_MULT);
  ALT(GL_RETURN);

  /* Alpha testing */
  ALT(GL_ALPHA_TEST);
  ALT(GL_ALPHA_TEST_REF);
  ALT(GL_ALPHA_TEST_FUNC);

  /* Blending */
  ALT(GL_BLEND);
  ALT(GL_BLEND_SRC);
  ALT(GL_BLEND_DST);
  ALT(GL_ZERO);
  ALT(GL_ONE);
  ALT(GL_SRC_COLOR);
  ALT(GL_ONE_MINUS_SRC_COLOR);
  ALT(GL_SRC_ALPHA);
  ALT(GL_ONE_MINUS_SRC_ALPHA);
  ALT(GL_DST_ALPHA);
  ALT(GL_ONE_MINUS_DST_ALPHA);
  ALT(GL_DST_COLOR);
  ALT(GL_ONE_MINUS_DST_COLOR);
  ALT(GL_SRC_ALPHA_SATURATE);

  /* Render Mode */
  ALT(GL_FEEDBACK);
  ALT(GL_RENDER);
  ALT(GL_SELECT);

  /* Feedback */
  ALT(GL_2D);
  ALT(GL_3D);
  ALT(GL_3D_COLOR);
  ALT(GL_3D_COLOR_TEXTURE);
  ALT(GL_4D_COLOR_TEXTURE);
  ALT(GL_POINT_TOKEN);
  ALT(GL_LINE_TOKEN);
  ALT(GL_LINE_RESET_TOKEN);
  ALT(GL_POLYGON_TOKEN);
  ALT(GL_BITMAP_TOKEN);
  ALT(GL_DRAW_PIXEL_TOKEN);
  ALT(GL_COPY_PIXEL_TOKEN);
  ALT(GL_PASS_THROUGH_TOKEN);
  ALT(GL_FEEDBACK_BUFFER_POINTER);
  ALT(GL_FEEDBACK_BUFFER_SIZE);
  ALT(GL_FEEDBACK_BUFFER_TYPE);

  /* Selection */
  ALT(GL_SELECTION_BUFFER_POINTER);
  ALT(GL_SELECTION_BUFFER_SIZE);

  /* Fog */
  ALT(GL_FOG);
  ALT(GL_FOG_MODE);
  ALT(GL_FOG_DENSITY);
  ALT(GL_FOG_COLOR);
  ALT(GL_FOG_INDEX);
  ALT(GL_FOG_START);
  ALT(GL_FOG_END);
  ALT(GL_LINEAR);
  ALT(GL_EXP);
  ALT(GL_EXP2);

  /* Logic Ops */
  ALT(GL_LOGIC_OP);
  ALT(GL_INDEX_LOGIC_OP);
  ALT(GL_COLOR_LOGIC_OP);
  ALT(GL_LOGIC_OP_MODE);
  ALT(GL_CLEAR);
  ALT(GL_SET);
  ALT(GL_COPY);
  ALT(GL_COPY_INVERTED);
  ALT(GL_NOOP);
  ALT(GL_INVERT);
  ALT(GL_AND);
  ALT(GL_NAND);
  ALT(GL_OR);
  ALT(GL_NOR);
  ALT(GL_XOR);
  ALT(GL_EQUIV);
  ALT(GL_AND_REVERSE);
  ALT(GL_AND_INVERTED);
  ALT(GL_OR_REVERSE);
  ALT(GL_OR_INVERTED);

  /* Stencil */
  ALT(GL_STENCIL_BITS);
  ALT(GL_STENCIL_TEST);
  ALT(GL_STENCIL_CLEAR_VALUE);
  ALT(GL_STENCIL_FUNC);
  ALT(GL_STENCIL_VALUE_MASK);
  ALT(GL_STENCIL_FAIL);
  ALT(GL_STENCIL_PASS_DEPTH_FAIL);
  ALT(GL_STENCIL_PASS_DEPTH_PASS);
  ALT(GL_STENCIL_REF);
  ALT(GL_STENCIL_WRITEMASK);
  ALT(GL_STENCIL_INDEX);
  ALT(GL_KEEP);
  ALT(GL_REPLACE);
  ALT(GL_INCR);
  ALT(GL_DECR);

  /* Buffers, Pixel Drawing/Reading */
  ALT(GL_NONE);
  ALT(GL_LEFT);
  ALT(GL_RIGHT);
  /*GL_FRONT					0x0404 */
  /*GL_BACK					0x0405 */
  /*GL_FRONT_AND_BACK				0x0408 */
  ALT(GL_FRONT_LEFT);
  ALT(GL_FRONT_RIGHT);
  ALT(GL_BACK_LEFT);
  ALT(GL_BACK_RIGHT);
  ALT(GL_AUX0);
  ALT(GL_AUX1);
  ALT(GL_AUX2);
  ALT(GL_AUX3);
  ALT(GL_COLOR_INDEX);
  ALT(GL_RED);
  ALT(GL_GREEN);
  ALT(GL_BLUE);
  ALT(GL_ALPHA);
  ALT(GL_LUMINANCE);
  ALT(GL_LUMINANCE_ALPHA);
  ALT(GL_ALPHA_BITS);
  ALT(GL_RED_BITS);
  ALT(GL_GREEN_BITS);
  ALT(GL_BLUE_BITS);
  ALT(GL_INDEX_BITS);
  ALT(GL_SUBPIXEL_BITS);
  ALT(GL_AUX_BUFFERS);
  ALT(GL_READ_BUFFER);
  ALT(GL_DRAW_BUFFER);
  ALT(GL_DOUBLEBUFFER);
  ALT(GL_STEREO);
  ALT(GL_BITMAP);
  ALT(GL_COLOR);
  ALT(GL_DEPTH);
  ALT(GL_STENCIL);
  ALT(GL_DITHER);
  ALT(GL_RGB);
  ALT(GL_RGBA);

  /* Implementation limits */
  ALT(GL_MAX_LIST_NESTING);
  ALT(GL_MAX_EVAL_ORDER);
  ALT(GL_MAX_LIGHTS);
  ALT(GL_MAX_CLIP_PLANES);
  ALT(GL_MAX_TEXTURE_SIZE);
  ALT(GL_MAX_PIXEL_MAP_TABLE);
  ALT(GL_MAX_ATTRIB_STACK_DEPTH);
  ALT(GL_MAX_MODELVIEW_STACK_DEPTH);
  ALT(GL_MAX_NAME_STACK_DEPTH);
  ALT(GL_MAX_PROJECTION_STACK_DEPTH);
  ALT(GL_MAX_TEXTURE_STACK_DEPTH);
  ALT(GL_MAX_VIEWPORT_DIMS);
  ALT(GL_MAX_CLIENT_ATTRIB_STACK_DEPTH);

  /* Gets */
  ALT(GL_ATTRIB_STACK_DEPTH);
  ALT(GL_CLIENT_ATTRIB_STACK_DEPTH);
  ALT(GL_COLOR_CLEAR_VALUE);
  ALT(GL_COLOR_WRITEMASK);
  ALT(GL_CURRENT_INDEX);
  ALT(GL_CURRENT_COLOR);
  ALT(GL_CURRENT_NORMAL);
  ALT(GL_CURRENT_RASTER_COLOR);
  ALT(GL_CURRENT_RASTER_DISTANCE);
  ALT(GL_CURRENT_RASTER_INDEX);
  ALT(GL_CURRENT_RASTER_POSITION);
  ALT(GL_CURRENT_RASTER_TEXTURE_COORDS);
  ALT(GL_CURRENT_RASTER_POSITION_VALID);
  ALT(GL_CURRENT_TEXTURE_COORDS);
  ALT(GL_INDEX_CLEAR_VALUE);
  ALT(GL_INDEX_MODE);
  ALT(GL_INDEX_WRITEMASK);
  ALT(GL_MODELVIEW_MATRIX);
  ALT(GL_MODELVIEW_STACK_DEPTH);
  ALT(GL_NAME_STACK_DEPTH);
  ALT(GL_PROJECTION_MATRIX);
  ALT(GL_PROJECTION_STACK_DEPTH);
  ALT(GL_RENDER_MODE);
  ALT(GL_RGBA_MODE);
  ALT(GL_TEXTURE_MATRIX);
  ALT(GL_TEXTURE_STACK_DEPTH);
  ALT(GL_VIEWPORT);

  /* Evaluators */
  ALT(GL_AUTO_NORMAL);
  ALT(GL_MAP1_COLOR_4);
  ALT(GL_MAP1_INDEX);
  ALT(GL_MAP1_NORMAL);
  ALT(GL_MAP1_TEXTURE_COORD_1);
  ALT(GL_MAP1_TEXTURE_COORD_2);
  ALT(GL_MAP1_TEXTURE_COORD_3);
  ALT(GL_MAP1_TEXTURE_COORD_4);
  ALT(GL_MAP1_VERTEX_3);
  ALT(GL_MAP1_VERTEX_4);
  ALT(GL_MAP2_COLOR_4);
  ALT(GL_MAP2_INDEX);
  ALT(GL_MAP2_NORMAL);
  ALT(GL_MAP2_TEXTURE_COORD_1);
  ALT(GL_MAP2_TEXTURE_COORD_2);
  ALT(GL_MAP2_TEXTURE_COORD_3);
  ALT(GL_MAP2_TEXTURE_COORD_4);
  ALT(GL_MAP2_VERTEX_3);
  ALT(GL_MAP2_VERTEX_4);
  ALT(GL_MAP1_GRID_DOMAIN);
  ALT(GL_MAP1_GRID_SEGMENTS);
  ALT(GL_MAP2_GRID_DOMAIN);
  ALT(GL_MAP2_GRID_SEGMENTS);
  ALT(GL_COEFF);
  ALT(GL_ORDER);
  ALT(GL_DOMAIN);

  /* Hints */
  ALT(GL_PERSPECTIVE_CORRECTION_HINT);
  ALT(GL_POINT_SMOOTH_HINT);
  ALT(GL_LINE_SMOOTH_HINT);
  ALT(GL_POLYGON_SMOOTH_HINT);
  ALT(GL_FOG_HINT);
  ALT(GL_DONT_CARE);
  ALT(GL_FASTEST);
  ALT(GL_NICEST);

  /* Scissor box */
  ALT(GL_SCISSOR_BOX);
  ALT(GL_SCISSOR_TEST);

  /* Pixel Mode / Transfer */
  ALT(GL_MAP_COLOR);
  ALT(GL_MAP_STENCIL);
  ALT(GL_INDEX_SHIFT);
  ALT(GL_INDEX_OFFSET);
  ALT(GL_RED_SCALE);
  ALT(GL_RED_BIAS);
  ALT(GL_GREEN_SCALE);
  ALT(GL_GREEN_BIAS);
  ALT(GL_BLUE_SCALE);
  ALT(GL_BLUE_BIAS);
  ALT(GL_ALPHA_SCALE);
  ALT(GL_ALPHA_BIAS);
  ALT(GL_DEPTH_SCALE);
  ALT(GL_DEPTH_BIAS);
  ALT(GL_PIXEL_MAP_S_TO_S_SIZE);
  ALT(GL_PIXEL_MAP_I_TO_I_SIZE);
  ALT(GL_PIXEL_MAP_I_TO_R_SIZE);
  ALT(GL_PIXEL_MAP_I_TO_G_SIZE);
  ALT(GL_PIXEL_MAP_I_TO_B_SIZE);
  ALT(GL_PIXEL_MAP_I_TO_A_SIZE);
  ALT(GL_PIXEL_MAP_R_TO_R_SIZE);
  ALT(GL_PIXEL_MAP_G_TO_G_SIZE);
  ALT(GL_PIXEL_MAP_B_TO_B_SIZE);
  ALT(GL_PIXEL_MAP_A_TO_A_SIZE);
  ALT(GL_PIXEL_MAP_S_TO_S);
  ALT(GL_PIXEL_MAP_I_TO_I);
  ALT(GL_PIXEL_MAP_I_TO_R);
  ALT(GL_PIXEL_MAP_I_TO_G);
  ALT(GL_PIXEL_MAP_I_TO_B);
  ALT(GL_PIXEL_MAP_I_TO_A);
  ALT(GL_PIXEL_MAP_R_TO_R);
  ALT(GL_PIXEL_MAP_G_TO_G);
  ALT(GL_PIXEL_MAP_B_TO_B);
  ALT(GL_PIXEL_MAP_A_TO_A);
  ALT(GL_PACK_ALIGNMENT);
  ALT(GL_PACK_LSB_FIRST);
  ALT(GL_PACK_ROW_LENGTH);
  ALT(GL_PACK_SKIP_PIXELS);
  ALT(GL_PACK_SKIP_ROWS);
  ALT(GL_PACK_SWAP_BYTES);
  ALT(GL_UNPACK_ALIGNMENT);
  ALT(GL_UNPACK_LSB_FIRST);
  ALT(GL_UNPACK_ROW_LENGTH);
  ALT(GL_UNPACK_SKIP_PIXELS);
  ALT(GL_UNPACK_SKIP_ROWS);
  ALT(GL_UNPACK_SWAP_BYTES);
  ALT(GL_ZOOM_X);
  ALT(GL_ZOOM_Y);

  /* Texture mapping */
  ALT(GL_TEXTURE_ENV);
  ALT(GL_TEXTURE_ENV_MODE);
  ALT(GL_TEXTURE_1D);
  ALT(GL_TEXTURE_2D);
  ALT(GL_TEXTURE_WRAP_S);
  ALT(GL_TEXTURE_WRAP_T);
  ALT(GL_TEXTURE_MAG_FILTER);
  ALT(GL_TEXTURE_MIN_FILTER);
  ALT(GL_TEXTURE_ENV_COLOR);
  ALT(GL_TEXTURE_GEN_S);
  ALT(GL_TEXTURE_GEN_T);
  ALT(GL_TEXTURE_GEN_R);
  ALT(GL_TEXTURE_GEN_Q);
  ALT(GL_TEXTURE_GEN_MODE);
  ALT(GL_TEXTURE_BORDER_COLOR);
  ALT(GL_TEXTURE_WIDTH);
  ALT(GL_TEXTURE_HEIGHT);
  ALT(GL_TEXTURE_BORDER);
  ALT(GL_TEXTURE_COMPONENTS);
  ALT(GL_TEXTURE_RED_SIZE);
  ALT(GL_TEXTURE_GREEN_SIZE);
  ALT(GL_TEXTURE_BLUE_SIZE);
  ALT(GL_TEXTURE_ALPHA_SIZE);
  ALT(GL_TEXTURE_LUMINANCE_SIZE);
  ALT(GL_TEXTURE_INTENSITY_SIZE);
  ALT(GL_NEAREST_MIPMAP_NEAREST);
  ALT(GL_NEAREST_MIPMAP_LINEAR);
  ALT(GL_LINEAR_MIPMAP_NEAREST);
  ALT(GL_LINEAR_MIPMAP_LINEAR);
  ALT(GL_OBJECT_LINEAR);
  ALT(GL_OBJECT_PLANE);
  ALT(GL_EYE_LINEAR);
  ALT(GL_EYE_PLANE);
  ALT(GL_SPHERE_MAP);
  ALT(GL_DECAL);
  ALT(GL_MODULATE);
  ALT(GL_NEAREST);
  ALT(GL_REPEAT);
  ALT(GL_CLAMP);
  ALT(GL_S);
  ALT(GL_T);
  ALT(GL_R);
  ALT(GL_Q);

  /* Utility */
  ALT(GL_VENDOR);
  ALT(GL_RENDERER);
  ALT(GL_VERSION);
  ALT(GL_EXTENSIONS);

  /* Errors */
  ALT(GL_NO_ERROR);
  ALT(GL_INVALID_ENUM);
  ALT(GL_INVALID_VALUE);
  ALT(GL_INVALID_OPERATION);
  ALT(GL_STACK_OVERFLOW);
  ALT(GL_STACK_UNDERFLOW);
  ALT(GL_OUT_OF_MEMORY);

  /* glPush/PopAttrib bits */
  ALT(GL_CURRENT_BIT);
  ALT(GL_POINT_BIT);
  ALT(GL_LINE_BIT);
  ALT(GL_POLYGON_BIT);
  ALT(GL_POLYGON_STIPPLE_BIT);
  ALT(GL_PIXEL_MODE_BIT);
  ALT(GL_LIGHTING_BIT);
  ALT(GL_FOG_BIT);
  ALT(GL_DEPTH_BUFFER_BIT);
  ALT(GL_ACCUM_BUFFER_BIT);
  ALT(GL_STENCIL_BUFFER_BIT);
  ALT(GL_VIEWPORT_BIT);
  ALT(GL_TRANSFORM_BIT);
  ALT(GL_ENABLE_BIT);
  ALT(GL_COLOR_BUFFER_BIT);
  ALT(GL_HINT_BIT);
  ALT(GL_EVAL_BIT);
  ALT(GL_LIST_BIT);
  ALT(GL_TEXTURE_BIT);
  ALT(GL_SCISSOR_BIT);
  ALT(GL_ALL_ATTRIB_BITS);

  /* OpenGL 1.1 */
  ALT(GL_PROXY_TEXTURE_1D);
  ALT(GL_PROXY_TEXTURE_2D);
  ALT(GL_TEXTURE_PRIORITY);
  ALT(GL_TEXTURE_RESIDENT);
  ALT(GL_TEXTURE_BINDING_1D);
  ALT(GL_TEXTURE_BINDING_2D);
  ALT(GL_TEXTURE_INTERNAL_FORMAT);
  ALT(GL_ALPHA4);
  ALT(GL_ALPHA8);
  ALT(GL_ALPHA12);
  ALT(GL_ALPHA16);
  ALT(GL_LUMINANCE4);
  ALT(GL_LUMINANCE8);
  ALT(GL_LUMINANCE12);
  ALT(GL_LUMINANCE16);
  ALT(GL_LUMINANCE4_ALPHA4);
  ALT(GL_LUMINANCE6_ALPHA2);
  ALT(GL_LUMINANCE8_ALPHA8);
  ALT(GL_LUMINANCE12_ALPHA4);
  ALT(GL_LUMINANCE12_ALPHA12);
  ALT(GL_LUMINANCE16_ALPHA16);
  ALT(GL_INTENSITY);
  ALT(GL_INTENSITY4);
  ALT(GL_INTENSITY8);
  ALT(GL_INTENSITY12);
  ALT(GL_INTENSITY16);
  ALT(GL_R3_G3_B2);
  ALT(GL_RGB4);
  ALT(GL_RGB5);
  ALT(GL_RGB8);
  ALT(GL_RGB10);
  ALT(GL_RGB12);
  ALT(GL_RGB16);
  ALT(GL_RGBA2);
  ALT(GL_RGBA4);
  ALT(GL_RGB5_A1);
  ALT(GL_RGBA8);
  ALT(GL_RGB10_A2);
  ALT(GL_RGBA12);
  ALT(GL_RGBA16);
  return "(unknown)";
}

END_NAMESPACE_GMGRAPHICS;
